version: "2"

run:
  timeout: 2m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - bodyclose
    - ineffassign
    - unused
    - sloglint

formatters:
  enable:
    - goimports
    - golines

linters-settings:
  golines:
    max-len: 120

  sloglint:
    no-global: default
    context: scope